"""phase A financial profile

Revision ID: 48ed3863cec4
Revises: 245fc8037e18
Create Date: 2026-06-18 01:36:48.221261
"""
from alembic import op
import sqlalchemy as sa


revision = '48ed3863cec4'
down_revision = '245fc8037e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('balance_inr', sa.Float(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_accounts_user_id'), 'cash_accounts', ['user_id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('loan_type', sa.String(length=16), nullable=False),
    sa.Column('lender', sa.String(length=128), nullable=False),
    sa.Column('principal_outstanding_inr', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('emi_inr', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('annual_interest_inr', sa.Float(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debts_user_id'), 'debts', ['user_id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('principal_inr', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('maturity_date', sa.String(length=10), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('monthly_inr', sa.Float(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('target_inr', sa.Float(), nullable=False),
    sa.Column('target_date', sa.String(length=10), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('saved_inr', sa.Float(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('income_profiles',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('hra_received', sa.Float(), nullable=False),
    sa.Column('special_allowance', sa.Float(), nullable=False),
    sa.Column('other_income', sa.Float(), nullable=False),
    sa.Column('rent_paid', sa.Float(), nullable=False),
    sa.Column('metro', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('policy_type', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('cover_inr', sa.Float(), nullable=False),
    sa.Column('annual_premium_inr', sa.Float(), nullable=False),
    sa.Column('term_years', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_user_id'), 'insurance_policies', ['user_id'], unique=False)
    op.create_table('mf_folios',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('scheme_code', sa.String(length=16), nullable=False),
    sa.Column('scheme_name', sa.String(length=255), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('sip_amount_inr', sa.Float(), nullable=False),
    sa.Column('sip_day', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mf_folios_user_id'), 'mf_folios', ['user_id'], unique=False)
    op.create_table('retirement_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('balance_inr', sa.Float(), nullable=False),
    sa.Column('annual_contribution_inr', sa.Float(), nullable=False),
    sa.Column('seed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retirement_accounts_user_id'), 'retirement_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retirement_accounts_user_id'), table_name='retirement_accounts')
    op.drop_table('retirement_accounts')
    op.drop_index(op.f('ix_mf_folios_user_id'), table_name='mf_folios')
    op.drop_table('mf_folios')
    op.drop_index(op.f('ix_insurance_policies_user_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_table('income_profiles')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_debts_user_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_cash_accounts_user_id'), table_name='cash_accounts')
    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
