"""phase G alert kinds

Revision ID: b2f8bf9660bd
Revises: 48ed3863cec4
Create Date: 2026-06-18 03:11:48.296101
"""
from alembic import op
import sqlalchemy as sa


revision = 'b2f8bf9660bd'
down_revision = '48ed3863cec4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'alerts',
        sa.Column('kind', sa.String(length=16), nullable=False, server_default='price'),
    )
    op.add_column('alerts', sa.Column('last_label', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'last_label')
    op.drop_column('alerts', 'kind')
    # ### end Alembic commands ###
