from typing import Any, Protocol


class CloudServices(Protocol):
    async def queue(self, topic: str, payload: Any) -> None: ...

    async def store(self, key: str, value: Any) -> None: ...

    async def fetch(self, key: str) -> Any: ...

    async def run(self, job: str, payload: Any) -> Any: ...

    async def ai(self, prompt: str, context: Any | None = None) -> str: ...
