"""Deterministic synthetic household generator.

Usage from repo root:
  PYTHONPATH=apps/server python -m tools.synthgen --tier small --seed 42
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from app.exceptions.engine import compute_exceptions
from app.exceptions.fixtures import demo_books
from app.offline_demo import TIERS, household

def _defects(seed: int, index: int) -> list[dict]:
    defects = []
    if index % 7 == 3:
        defects.append({"kind": "name_variant", "field": "household_name"})
    if index % 11 == 2:
        defects.append({"kind": "duplicate_folio", "field": "lots"})
    if index % 13 == 1:
        defects.append({"kind": "missing_field", "field": "tax.hra_received"})
    return defects


def bundle(tier: str, seed: int) -> dict:
    count = TIERS[tier]
    sample_n = min(count, 10)
    households = []
    for index in range(sample_n):
        book = household(index, seed)
        if index % 7 == 3:
            book.household_name = book.household_name + " kumar"
        hits = compute_exceptions(book)
        households.append({
            "id": book.household_id,
            "name": book.household_name,
            "asOf": book.as_of.isoformat(),
            "tax": book.tax.model_dump(mode="json") if book.tax else None,
            "lots": [lot.model_dump(mode="json") for lot in book.lots],
            "exceptions": [
                {"ruleId": hit.rule_id, "rupeeDelta": hit.rupee_delta,
                 "fingerprint": hit.fingerprint}
                for hit in hits
            ],
            "defects": _defects(seed, index),
            "synthetic": True,
            "seed": seed,
        })
    return {
        "tier": tier,
        "seed": seed,
        "count": count,
        "sample": sample_n,
        "firms": [{"id": "firm_northstar", "name": "Northstar Private", "synthetic": True}],
        "households": households,
        "groundTruth": [row["defects"] for row in households],
        "note": "Fake PANs and books. Not real people. Large tier is generated by index.",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tier", choices=["small", "medium", "large"], default="small")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    payload = bundle(args.tier, args.seed)
    out = Path("tools/synthgen/out")
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{args.tier}.json"
    path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {path} count={payload['count']} sample={payload['sample']}")


if __name__ == "__main__":
    main()
